### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by bpvarsity** [jaalto/project--restricted-shell-rbash#1]
ERROR: --shell program does not exist:

**Comment by jaalto** [comment]
Need more information. Could you please give full command line used (copy lines from terminal). Run program through "bash -x PROGRAM" if needed to get more details to the bug report.

**Comment by jaalto** [comment]
I believe this is fixed in latest commit: b30b78a0c23cb4766721843cd0eef8171b918213
Please report back if needed.
