### ISSUE TITLE
enable CD command

### ISSUE THREAD

**Issue by bitchecker** [jaalto/project--restricted-shell-rbash#3]
There is a way to workaround of the "stupid" restricion of use the `cd` command of rbash?

I think that `cd` command is less risky than others.

**Comment by jaalto** [comment]
I'm not sure that this can be circumvented because cd is a built-in command in the interpreter.

**Comment by jaalto** [comment]
Closing because there is nothing that can be done due to limitations of rbash(1). A MESSAGE about this limitation is displayed during the execution of the makefile.sh (the program).
